let num;
console.log(num);
console.log(typeof num);
console.log("------------");
num = 10;
console.log(num);
console.log(typeof num);
console.log("------------");
num = "test"
console.log(num);
console.log(typeof num);
console.log("------------");
num = [];
console.log(num);
console.log(typeof num);
console.log("------------");
num = { name: "test" };
console.log(num);
console.log(typeof num);
console.log("------------");
num = 10.123;
console.log(num);
console.log(typeof num);
console.log("------------");
console.log("한국말");
console.log("------------");
age = 100;
console.log(age);
console.log(typeof age);
console.log("------------");
const c = 100;
console.log(c);
console.log(typeof c);
console.log("------------");
// type error
// c = 1000;
// console.log(c);
// console.log(typeof c);
// console.log("------------");